"""Pack loader: Pydantic models for world-pack manifests, seed states, and scenario briefs.

Supports two pack modes:
  static  — hand-authored seed_state.yaml + opening_scene.md, loaded as-is on New Game
  dynamic — world.md + scenario.yaml; seed generated by engine.generate_seed() each New Game

The models here are the schema-of-record for:
  Tool A — generate_seed(pack, overrides) -> SeedEnvelope      [this PR]
  Tool B — PlayerOverrides wiring (UI deferred)                 [designed-in]
  Tool C — generate_pack(theme) -> Pack (future PR)             [designed-in]
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, Field, model_validator

from ccya.models import CampaignArc, InventoryItem


_log = logging.getLogger(__name__)


class SeedPC(BaseModel):
    name: str
    tagline: str = ""
    bio: str = ""
    stats: dict[str, int] = Field(default_factory=dict)
    conditions: list[str] = Field(default_factory=list)
    momentum: int = 0
    drive: str = ""


class SeedLocation(BaseModel):
    id: str
    name: str
    description: str = ""


class CompendiumEntry(BaseModel):
    model_config = {"extra": "allow"}
    name: str | None = None
    title: str | None = None
    bio: str | None = None


class SeedCompendium(BaseModel):
    npcs: dict[str, CompendiumEntry] = Field(default_factory=dict)


class SeedScene(BaseModel):
    tagline: str = ""
    tags: list[str] = Field(default_factory=list)
    world_state: list[str] = Field(default_factory=list)
    recent_events: list[str] = Field(default_factory=list)
    present_npcs: list[dict[str, Any]] = Field(default_factory=list)


class SeedState(BaseModel):
    """Full validated game state shape — used for static load and dynamic seed writing.

    NOTE: StateDelta.inventory_add has max_length=6 (per-turn add cap).
    SeedState allows up to 12 — scenario.yaml inventory_size_range is the soft
    generator guidance; 12 is the hard ceiling for any hand-authored static pack.
    """

    meta: dict[str, Any]
    pc: SeedPC
    location: SeedLocation
    inventory: list[InventoryItem] = Field(min_length=1, max_length=12)
    scene: SeedScene
    compendium: SeedCompendium = Field(default_factory=SeedCompendium)
    arc: CampaignArc | None = None


class SeedEnvelope(BaseModel):
    """Output schema for the generate_seed LLM call.

    The LLM may populate compendium.npcs at seed time with 2-3 additional
    NPCs (name, title, bio). These are known-to-but-not-present in the
    opening scene. Do NOT set meta.compendium_touch_order — engine manages
    that field at runtime.
    """

    seed_state: SeedState
    opening_narrative: str = Field(min_length=50)
    actions: list[str] = Field(min_length=4, max_length=4)
    arc: CampaignArc | None = None
    pc_drive: str = ""


class Faction(BaseModel):
    id: str
    name: str
    description: str
    disposition: str = "neutral"


class NamedLocation(BaseModel):
    id: str
    name: str
    type: str
    description: str


class Constraints(BaseModel):
    min_named_npcs: int = 2
    inventory_size_range: tuple[int, int] = (4, 8)
    pc_stat_range: tuple[int, int] = (1, 4)
    pc_stat_total_range: tuple[int, int] = (12, 18)
    prose_word_range: tuple[int, int] = (200, 500)
    required_inventory_kinds: list[str] = Field(default_factory=list)
    npc_distinct_first_letters: bool = True
    forbid_cliches: list[str] = Field(default_factory=list)


class Inspiration(BaseModel):
    pc: str = ""
    inventory: str = ""
    npcs: str = ""


class PoolEntry(BaseModel):
    """Base entry for archetype pools (situation, arc, character, moral)."""

    id: str
    tags: list[str] = Field(default_factory=list)
    incompatible_with: list[str] = Field(default_factory=list)


class ScenarioBrief(BaseModel):
    """Complete world definition for a generated pack.

    Sections:
      constraints   — hard numeric rules for seed generation
      world_name    — short evocative name for the world (LLM-generated)
      world_facts   — 3–8 durable facts injected into world_state (replaces world.md)
      narrator_rules — tone/style rules injected into narrate system prompt (replaces style.md)
      world_rules   — 0–5 hard physical laws of the world (rendered as ## Universe rules)
      factions      — 3–6 named power groups injected into narrate context each turn
      locations     — 5–10 named places injected into narrate context each turn
      name_locales  — weighted Faker locales for name generation
      name_seed     — int; controls name selection randomness at generate time
      inspiration   — quality anti-pattern guidance for seed generation (no concrete examples)
    """
    world_name: str = ""
    constraints: Constraints = Field(default_factory=Constraints)
    world_facts: list[str] = Field(default_factory=list, max_length=8)
    narrator_rules: list[str] = Field(default_factory=list, max_length=12)
    world_rules: list[str] = Field(default_factory=list, max_length=5)
    factions: list[Faction] = Field(default_factory=list, max_length=6)
    locations: list[NamedLocation] = Field(default_factory=list, max_length=10)
    name_locales: list[dict[str, Any]] = Field(default_factory=list)
    name_seed: int = 0
    inspiration: Inspiration = Field(default_factory=Inspiration)
    situation_archetypes: list[PoolEntry] = Field(default_factory=list, max_length=16)
    arc_categories: list[PoolEntry] = Field(default_factory=list, max_length=20)
    character_dynamics: list[PoolEntry] = Field(default_factory=list, max_length=12)
    moral_pressures: list[PoolEntry] = Field(default_factory=list, max_length=10)


class WorldBrief(BaseModel):
    """Player input for generate_pack(). Five structured sections + one free-form.

    Each section drives a distinct part of world generation:
      concept       — the one-line pitch ("post-flood survival", "1930s supernatural noir")
      tone          — feel and register ("grim survival", "darkly comedic", "tense political")
      geography     — what the physical world looks like and how it shapes daily life
      power         — who holds power, how it was won, what it costs ordinary people
      daily_life    — what people eat, trade, fear, and talk about (grounds the narrator)
      player_hint   — optional: what kind of person the player wants to be (soft guidance)
    """
    concept: str
    tone: str = ""
    geography: str = ""
    power: str = ""
    daily_life: str = ""
    player_hint: str = ""


class GeneratedPackMeta(BaseModel):
    """Written into pack.yaml for generated packs. Marks provenance."""
    generated: bool = True
    world_brief_concept: str = ""


class PlayerOverrides(BaseModel):
    """Optional player-supplied tweaks at New Game time. All fields default empty.
    Engine injects into generate_seed prompt as soft guidance — Pydantic constraints
    and world.md canon win on conflict."""

    pc_hints: str = ""
    npc_hints: str = ""
    location_hints: str = ""
    free_form: str = ""
    npc_count: int = 0  # 0 = use pack default (scenario.constraints.min_named_npcs)
    arc_hints: str = ""
    drive_hint: str = ""

    def is_empty(self) -> bool:
        return not any(
            [
                self.pc_hints,
                self.npc_hints,
                self.location_hints,
                self.free_form,
                self.npc_count,
                self.arc_hints,
                self.drive_hint,
            ]
        )


class PackManifest(BaseModel):
    model_config = {"extra": "ignore"}
    id: str
    name: str
    description: str = ""
    genre: str = ""
    mode: str = "dynamic"
    tone_tags: list[str] = Field(default_factory=list)
    baseline_facts: list[str] = Field(default_factory=list, max_length=3)
    name_locales: list[dict[str, Any]] = Field(default_factory=list)
    use_male_only_names: bool = False


class Pack(BaseModel):
    manifest: PackManifest
    # Legacy text fields (world.md / style.md — still loaded for old packs)
    world_text: str = ""
    style_text: str = ""
    # Static mode
    seed: SeedState | None = None
    opening_text: str = ""
    opening_actions: list[str] = Field(default_factory=list)
    # Generated mode (new consolidated scenario.yaml)
    scenario: ScenarioBrief | None = None

    @property
    def mode(self) -> str:
        """Return 'static' or 'dynamic' based on which fields are populated."""
        if self.seed is not None:
            return "static"
        return "dynamic"

    @model_validator(mode="after")
    def _check_playable(self) -> "Pack":
        if self.seed is None and self.scenario is None:
            raise ValueError(
                "Pack must have either seed_state.yaml (static) or scenario.yaml (generated)"
            )
        return self


def _resolve_pack_dir(pack_id: str, packs_dir: Path) -> Path:
    """Resolve pack_id to a directory.

    Accepts:
      "flooded-world"          -> searches packs/default/, then packs/custom/
      "default/flooded-world"  -> packs/default/flooded-world
      "custom/my-world"        -> packs/custom/my-world
    """
    if "/" in pack_id:
        namespace, slug = pack_id.split("/", 1)
        candidate = packs_dir / namespace / slug
        if not candidate.is_dir():
            raise FileNotFoundError(f"Pack not found: {candidate}")
        return candidate
    # Check for pack directly under packs_dir (no namespace) first — supports
    # eval packs and any other flat pack layout.
    candidate = packs_dir / pack_id
    if candidate.is_dir():
        return candidate
    for namespace in ("default", "custom"):
        candidate = packs_dir / namespace / pack_id
        if candidate.is_dir():
            return candidate
    raise FileNotFoundError(f"Pack '{pack_id}' not found in {packs_dir}")


def load_pack(pack_id: str, packs_dir: Path) -> Pack:
    pack_dir = _resolve_pack_dir(pack_id, packs_dir)

    manifest_path = pack_dir / "pack.yaml"
    if not manifest_path.exists():
        raise FileNotFoundError(f"Missing pack.yaml in {pack_dir}")
    with open(manifest_path) as f:
        manifest_data = yaml.safe_load(f) or {}
    manifest = PackManifest(**manifest_data)

    def _read(filename: str, default: str = "") -> str:
        p = pack_dir / filename
        return p.read_text() if p.exists() else default

    def _read_yaml(filename: str) -> dict[str, Any]:
        p = pack_dir / filename
        if not p.exists():
            return {}
        with open(p) as f:
            return yaml.safe_load(f) or {}

    seed: SeedState | None = None
    opening_text = ""
    opening_actions: list[str] = []
    world_text = ""
    scenario: ScenarioBrief | None = None

    # Static mode: seed_state.yaml + opening_scene.md
    seed_path = pack_dir / "seed_state.yaml"
    if seed_path.exists():
        seed_data = _read_yaml("seed_state.yaml")
        opening_actions = seed_data.pop("opening_actions", [])
        if seed_data:
            seed = SeedState(**seed_data)
        opening_text = _read("opening_scene.md", "")

    # Dynamic mode: scenario.yaml (new consolidated schema)
    scenario_path = pack_dir / "scenario.yaml"
    if scenario_path.exists():
        scenario_data = _read_yaml("scenario.yaml")
        if scenario_data:
            scenario = ScenarioBrief(**scenario_data)

    # Legacy fallback: world.md and style.md (old dynamic packs)
    world_text = _read("world.md", "")
    style_text = _read("style.md", "")

    return Pack(
        manifest=manifest,
        world_text=world_text,
        style_text=style_text,
        seed=seed,
        opening_text=opening_text,
        opening_actions=opening_actions,
        scenario=scenario,
    )


def list_packs(packs_dir: Path) -> list[PackManifest]:
    manifests: list[PackManifest] = []
    if not packs_dir.is_dir():
        return manifests
    search_dirs = [
        packs_dir / "generated",
        packs_dir / "default",
        packs_dir / "custom",
    ]
    seen: set[str] = set()
    for search in search_dirs:
        if not search.is_dir():
            continue
        for child in sorted(search.iterdir()):
            if not child.is_dir():
                continue
            manifest_path = child / "pack.yaml"
            if manifest_path.exists() and child.name not in seen:
                seen.add(child.name)
                try:
                    with open(manifest_path) as f:
                        data = yaml.safe_load(f) or {}
                    manifests.append(PackManifest(**data))
                except Exception as err:
                    _log.warning("Skipping invalid pack manifest at %s: %s", manifest_path, err)

    return manifests


def parse_world_facts(world_md: str) -> list[str]:
    facts: list[str] = []
    for line in world_md.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if len(line) >= 2 and line[0] in "-*+" and line[1] == " ":
            line = line[2:].strip()
        if line:
            facts.append(line)
    return facts
