"""Pack loader: Pydantic models for world-pack manifests, seed states, and scenario briefs.

Supports two pack modes:
  static  — hand-authored seed_state.yaml + opening_scene.md, loaded as-is on New Game
  dynamic — world.md + scenario.yaml; seed generated by engine.generate_seed() each New Game

The models here are the schema-of-record for:
  Tool A — generate_seed(pack, overrides) -> SeedEnvelope      [this PR]
  Tool B — PlayerOverrides wiring (UI deferred)                 [designed-in]
  Tool C — generate_pack(theme) -> Pack (future PR)             [designed-in]
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Literal

import yaml
from pydantic import BaseModel, Field, field_validator, model_validator

from ccya.models import InventoryItem, NpcRef


# ---------------------------------------------------------------------------
# Seed state sub-models
# ---------------------------------------------------------------------------


class SeedPC(BaseModel):
    name: str
    tagline: str = ""
    bio: str = ""
    stats: dict[str, int] = Field(default_factory=dict)
    conditions: list[str] = Field(default_factory=list)

    @model_validator(mode="before")
    @classmethod
    def _migrate_concept(cls, v: Any) -> Any:
        """v3 renamed pc.concept → pc.tagline; accept either on load."""
        if isinstance(v, dict) and "concept" in v and "tagline" not in v:
            v = dict(v)
            v["tagline"] = v.pop("concept")
        return v


class SeedLocation(BaseModel):
    id: str
    name: str
    description: str = ""


class SeedQuestObjective(BaseModel):
    description: str
    done: bool = False
    failed: bool = False


class SeedQuest(BaseModel):
    id: str
    title: str
    status: str = "active"
    objectives: list[SeedQuestObjective] = Field(default_factory=list)


class CompendiumEntry(BaseModel):
    model_config = {"extra": "allow"}
    name: str | None = None
    title: str | None = None
    bio: str | None = None


class SeedCompendium(BaseModel):
    npcs: dict[str, CompendiumEntry] = Field(default_factory=dict)


class SeedScene(BaseModel):
    tagline: str = ""
    tags: list[str] = Field(default_factory=list)
    present_npcs: list[NpcRef] = Field(default_factory=list)
    established_facts: list[str] = Field(default_factory=list)


class SeedState(BaseModel):
    """Full validated game state shape — used for static load and dynamic seed writing.

    NOTE: StateDelta.inventory_add has max_length=6 (per-turn add cap).
    SeedState allows up to 12 — scenario.yaml inventory_size_range is the soft
    generator guidance; 12 is the hard ceiling for any hand-authored static pack.
    """

    meta: dict[str, Any]
    pc: SeedPC
    location: SeedLocation
    inventory: list[InventoryItem] = Field(min_length=1, max_length=12)
    quests: list[SeedQuest] = Field(min_length=1)
    scene: SeedScene
    compendium: SeedCompendium = Field(default_factory=SeedCompendium)


class SeedEnvelope(BaseModel):
    """Output schema for the generate_seed LLM call.

    The LLM must NOT populate compendium.npcs or meta.compendium_touch_order —
    those are engine-managed and start empty on every new game.
    """

    seed_state: SeedState
    opening_narrative: str = Field(min_length=50)


# ---------------------------------------------------------------------------
# Scenario brief (dynamic mode only)
# ---------------------------------------------------------------------------


class Constraints(BaseModel):
    # required-presence
    min_named_npcs: int = 2
    min_objectives_per_quest: int = 2
    starting_quest_count: int = 1
    # ranges
    inventory_size_range: tuple[int, int] = (4, 8)
    pc_stat_range: tuple[int, int] = (1, 4)
    pc_stat_total_range: tuple[int, int] = (8, 12)
    prose_word_range: tuple[int, int] = (200, 500)
    # composition
    required_inventory_kinds: list[str] = Field(default_factory=list)
    npc_distinct_first_letters: bool = True
    # creativity guards (ASCII field name; yaml key also "forbid_cliches")
    forbid_cliches: list[str] = Field(default_factory=list)
    forbid_player_dependents: bool = True
    forbid_legendary_items: bool = True


class Inspiration(BaseModel):
    pc: str = ""
    opening_situation: str = ""
    npcs: str = ""
    inventory: str = ""
    quests: str = ""


class ScenarioBrief(BaseModel):
    constraints: Constraints = Field(default_factory=Constraints)
    inspiration: Inspiration = Field(default_factory=Inspiration)


# ---------------------------------------------------------------------------
# Player overrides — Tool B (wiring built, UI deferred)
# ---------------------------------------------------------------------------


class PlayerOverrides(BaseModel):
    """Optional player-supplied tweaks at New Game time. All fields default empty.
    Engine injects into generate_seed prompt as soft guidance — Pydantic constraints
    and world.md canon win on conflict."""

    pc_hints: str = ""
    npc_hints: str = ""
    location_hints: str = ""
    quest_hints: str = ""
    free_form: str = ""

    def is_empty(self) -> bool:
        return not any([
            self.pc_hints, self.npc_hints,
            self.location_hints, self.quest_hints, self.free_form,
        ])


# ---------------------------------------------------------------------------
# Extract examples
# ---------------------------------------------------------------------------


class ExtractExample(BaseModel):
    title: str
    thinking: str = ""
    json_text: str = Field(alias="json")

    model_config = {"populate_by_name": True}

    @field_validator("json_text", mode="after")
    @classmethod
    def _validate_json(cls, v: str) -> str:
        try:
            json.loads(v)
        except json.JSONDecodeError as exc:
            raise ValueError(f"extract example 'json' is not valid JSON: {exc}") from exc
        return v


# ---------------------------------------------------------------------------
# Pack manifest and files
# ---------------------------------------------------------------------------


class PackFiles(BaseModel):
    # static mode
    seed: str | None = None
    opening: str | None = None
    # dynamic mode
    world: str | None = None
    scenario: str | None = None
    # both modes (optional)
    style: str | None = None
    extract_examples: str | None = None


class PackManifest(BaseModel):
    id: str
    name: str
    description: str = ""
    genre: str = ""
    tone_tags: list[str] = Field(default_factory=list)
    version: int = 1
    mode: Literal["static", "dynamic"]
    files: PackFiles = Field(default_factory=PackFiles)


# ---------------------------------------------------------------------------
# Assembled Pack object
# ---------------------------------------------------------------------------


class Pack(BaseModel):
    manifest: PackManifest
    style_text: str = ""
    extract_examples: list[ExtractExample] = Field(default_factory=list)
    # static-mode fields
    seed: SeedState | None = None
    opening_text: str = ""
    # dynamic-mode fields
    world_text: str = ""
    scenario: ScenarioBrief | None = None

    @model_validator(mode="after")
    def _check_mode_files(self) -> "Pack":
        mode = self.manifest.mode
        if mode == "static":
            if self.seed is None:
                raise ValueError("static pack requires seed (seed_state.yaml)")
            if not self.opening_text:
                raise ValueError("static pack requires opening_text (opening_scene.md)")
        elif mode == "dynamic":
            if not self.world_text:
                raise ValueError("dynamic pack requires world_text (world.md)")
            if self.scenario is None:
                raise ValueError("dynamic pack requires scenario (scenario.yaml)")
        return self


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def load_pack(pack_id: str, packs_dir: Path) -> Pack:
    """Load and validate a pack from disk. Raises FileNotFoundError / ValidationError on bad input."""
    pack_dir = packs_dir / pack_id
    if not pack_dir.is_dir():
        raise FileNotFoundError(f"Pack directory not found: {pack_dir}")

    manifest_path = pack_dir / "pack.yaml"
    if not manifest_path.exists():
        raise FileNotFoundError(f"Missing pack.yaml in {pack_dir}")
    with open(manifest_path) as f:
        manifest_data = yaml.safe_load(f) or {}
    manifest = PackManifest(**manifest_data)

    def _read(filename: str | None, default: str = "") -> str:
        if not filename:
            return default
        p = pack_dir / filename
        return p.read_text() if p.exists() else default

    def _read_yaml(filename: str | None) -> dict:
        if not filename:
            return {}
        p = pack_dir / filename
        if not p.exists():
            return {}
        with open(p) as f:
            return yaml.safe_load(f) or {}

    files = manifest.files
    seed: SeedState | None = None
    opening_text = ""
    world_text = ""
    scenario: ScenarioBrief | None = None

    if manifest.mode == "static":
        seed_data = _read_yaml(files.seed or "seed_state.yaml")
        if seed_data:
            seed = SeedState(**seed_data)
        opening_text = _read(files.opening or "opening_scene.md")
    else:
        world_text = _read(files.world or "world.md")
        scenario_data = _read_yaml(files.scenario or "scenario.yaml")
        if scenario_data:
            scenario = ScenarioBrief(**scenario_data)

    style_text = _read(files.style or "style.md")

    extract_examples: list[ExtractExample] = []
    examples_data = _read_yaml(files.extract_examples or "extract_examples.yaml")
    for ex in examples_data.get("examples", []):
        extract_examples.append(ExtractExample(**ex))

    return Pack(
        manifest=manifest,
        style_text=style_text,
        extract_examples=extract_examples,
        seed=seed,
        opening_text=opening_text,
        world_text=world_text,
        scenario=scenario,
    )


def list_packs(packs_dir: Path) -> list[PackManifest]:
    """Return manifests for all valid packs in packs_dir, sorted by id."""
    manifests: list[PackManifest] = []
    if not packs_dir.is_dir():
        return manifests
    for child in sorted(packs_dir.iterdir()):
        manifest_path = child / "pack.yaml"
        if manifest_path.exists():
            try:
                with open(manifest_path) as f:
                    data = yaml.safe_load(f) or {}
                manifests.append(PackManifest(**data))
            except Exception:
                pass
    return manifests


def parse_world_facts(world_md: str) -> list[str]:
    """Parse world.md into a list of established facts (one per non-blank, non-heading line).

    Rules:
    - Skip headings (lines starting with #) and blank lines
    - Bullet lines (- * +): strip bullet marker, use remainder as fact
    - Other non-empty lines: include as-is
    """
    facts: list[str] = []
    for line in world_md.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if len(line) >= 2 and line[0] in "-*+" and line[1] == " ":
            line = line[2:].strip()
        if line:
            facts.append(line)
    return facts
