#!/usr/bin/env python3
"""Generate roadmap/index.md (active) and roadmap/archive-index.md from YAML frontmatter."""
from pathlib import Path
import yaml
import sys
import tempfile
import os
import re

ROADMAP_DIR = Path("roadmap")
BUGS_DIR = ROADMAP_DIR / "bugs"
FEATURES_DIR = ROADMAP_DIR / "features"
INDEX_FILE = ROADMAP_DIR / "index.md"
ARCHIVE_INDEX_FILE = ROADMAP_DIR / "archive-index.md"

STATUS_ORDER = ["idea", "scoping", "up-next", "new", "validated", "done", "canceled"]
ACTIVE_STATUSES = {"idea", "scoping", "up-next", "new", "validated"}
ARCHIVE_STATUSES = {"done", "canceled"}

BUCKET_ORDER = ["Balancing", "Extraction", "Tech Debt", "Tooling", "UI", "World Building"]

SECTION_MAP = {
    "idea": "Idea",
    "scoping": "Scoping",
    "up-next": "Queued",
    "new": "New",
    "validated": "Validating",
    "done": "Done",
    "canceled": "Canceled",
}

URGENCY_LABELS = {1: "urgent", 2: "high", 3: "medium", 4: "low"}

PREFIX_RE = re.compile(r'^\[.*?\]\s*')
PRIORITY_RE = re.compile(r'^(1|2|3|4)\. ')


def strip_prefix(title: str) -> str:
    s = PREFIX_RE.sub("", title)
    s = PRIORITY_RE.sub("", s)
    return s.strip()


def get_bucket(labels: list) -> str:
    for lbl in labels:
        if lbl in BUCKET_ORDER:
            return lbl
    return "Other"


def urgency_label(n: int) -> str:
    return URGENCY_LABELS.get(n, str(n))


def parse_frontmatter(path: Path) -> dict | None:
    text = path.read_text()
    if not text.startswith("---"):
        print(f"  WARN {path.relative_to('.')} has no frontmatter, skipping", file=sys.stderr)
        return None
    parts = text.split("---", 2)
    if len(parts) < 3:
        print(f"  WARN {path.relative_to('.')} malformed frontmatter, skipping", file=sys.stderr)
        return None
    try:
        return yaml.safe_load(parts[1])
    except yaml.YAMLError as e:
        print(f"  WARN {path.relative_to('.')} frontmatter parse error: {e}", file=sys.stderr)
        return None


ARCHIVE_DIR = ROADMAP_DIR / "archive"


def load_entries(directory: Path, is_archive: bool = False) -> list[dict]:
    entries = []
    if not directory.exists():
        return entries
    for f in sorted(directory.glob("*.md")):
        if f.name in ("index.md", "archive-index.md"):
            continue
        fm = parse_frontmatter(f)
        if fm is None:
            continue
        fm["_path"] = f
        fm.setdefault("status", "unknown")
        if not is_archive:
            fm.setdefault("urgency", 3)
            fm.setdefault("size", "unknown")
        fm.setdefault("created", "unknown")
        fm.setdefault("title", f.stem.replace("-", " ").title())
        fm.setdefault("labels", [])
        entries.append(fm)
    return entries


def emit_table(lines: list[str], entries: list[dict], show_size: bool) -> None:
    if show_size:
        lines.append("| Title | Urgency | Size | Created |")
        lines.append("|---|---|---|---|")
        for e in entries:
            title = strip_prefix(e.get("title", "Untitled"))
            urg = urgency_label(e.get("urgency", 3))
            size = e.get("size", "?")
            created = e.get("created", "?")
            lines.append(f"| {title} | {urg} | {size} | {created} |")
    else:
        lines.append("| Title | Created |")
        lines.append("|---|---|")
        for e in entries:
            title = strip_prefix(e.get("title", "Untitled"))
            created = e.get("created", "?")
            lines.append(f"| {title} | {created} |")
    lines.append("")


def write_sections(filepath: Path, entries: list[dict], show_size: bool) -> int:
    lines = []
    lines.append("Auto-generated by scripts/generate-roadmap.py. Do not edit manually.")
    lines.append("")

    present = {e["status"] for e in entries}
    for status in STATUS_ORDER:
        if status not in present:
            continue
        status_entries = [e for e in entries if e["status"] == status]
        if not status_entries:
            continue
        section = SECTION_MAP.get(status, status.replace("-", " ").title())
        lines.append(f"## {section}")
        lines.append("")

        bucket_groups: dict[str, list[dict]] = {}
        for e in status_entries:
            bucket = get_bucket(e["labels"])
            bucket_groups.setdefault(bucket, []).append(e)

        for bucket in BUCKET_ORDER:
            group = bucket_groups.pop(bucket, None)
            if group:
                lines.append(f"**{bucket}**")
                lines.append("")
                emit_table(lines, group, show_size)

        if bucket_groups:
            for bucket, group in sorted(bucket_groups.items()):
                lines.append(f"**{bucket}**")
                lines.append("")
                emit_table(lines, group, show_size)

    content = "\n".join(lines)
    fd, tmp_path = tempfile.mkstemp(dir=ROADMAP_DIR, suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp_path, filepath)
    except Exception:
        os.unlink(tmp_path)
        raise

    return len(entries)


def main():
    active = load_entries(BUGS_DIR) + load_entries(FEATURES_DIR)
    archived = load_entries(ARCHIVE_DIR, is_archive=True)

    active.sort(key=lambda e: (
        BUCKET_ORDER.index(get_bucket(e["labels"])) if get_bucket(e["labels"]) in BUCKET_ORDER else len(BUCKET_ORDER),
        e["urgency"],
        e["created"],
    ))

    archived.sort(key=lambda e: (
        BUCKET_ORDER.index(get_bucket(e["labels"])) if get_bucket(e["labels"]) in BUCKET_ORDER else len(BUCKET_ORDER),
        e["created"],
    ))

    n_active = write_sections(INDEX_FILE, active, show_size=True)
    n_archive = write_sections(ARCHIVE_INDEX_FILE, archived, show_size=False)
    print(f"Wrote {INDEX_FILE} ({n_active} entries)")
    print(f"Wrote {ARCHIVE_INDEX_FILE} ({n_archive} entries)")


if __name__ == "__main__":
    main()
