#!/usr/bin/env python3
"""Generate roadmap/index.md from YAML frontmatter in roadmap/bugs/ and roadmap/features/."""
from pathlib import Path
import yaml
import sys
import tempfile
import os

ROADMAP_DIR = Path("roadmap")
BUGS_DIR = ROADMAP_DIR / "bugs"
FEATURES_DIR = ROADMAP_DIR / "features"
INDEX_FILE = ROADMAP_DIR / "index.md"

STATUS_ORDER = [
    "idea",
    "scoping",
    "up-next",
    "validated",
    "done",
    "canceled",
]

TYPE_LABELS = {
    "bug": "Bug",
    "feature": "Feature",
}


def parse_frontmatter(path: Path) -> dict | None:
    """Parse YAML frontmatter from a markdown file. Returns None if no frontmatter."""
    text = path.read_text()
    if not text.startswith("---"):
        print(f"  WARN {path.relative_to('.')} has no frontmatter, skipping", file=sys.stderr)
        return None
    parts = text.split("---", 2)
    if len(parts) < 3:
        print(f"  WARN {path.relative_to('.')} malformed frontmatter, skipping", file=sys.stderr)
        return None
    try:
        return yaml.safe_load(parts[1])
    except yaml.YAMLError as e:
        print(f"  WARN {path.relative_to('.')} frontmatter parse error: {e}", file=sys.stderr)
        return None


def main():
    entries: list[dict] = []
    for directory in (BUGS_DIR, FEATURES_DIR):
        if not directory.exists():
            continue
        for f in sorted(directory.glob("*.md")):
            if f.name == "index.md":
                continue
            fm = parse_frontmatter(f)
            if fm is None:
                continue
            fm["_path"] = f
            fm["_type"] = "bug" if f.parent == BUGS_DIR else "feature"
            fm.setdefault("status", "unknown")
            fm.setdefault("urgency", 3)
            fm.setdefault("size", "unknown")
            fm.setdefault("created", "unknown")
            fm.setdefault("title", f.stem.replace("-", " ").title())
            fm.setdefault("labels", [])
            entries.append(fm)

    # Sort by urgency (1→4), then created date (oldest first)
    entries.sort(key=lambda e: (e["urgency"], e["created"]))

    lines: list[str] = []
    lines.append("Auto-generated by scripts/generate-roadmap.py. Do not edit manually.")
    lines.append("")

    for status in STATUS_ORDER:
        status_entries = [e for e in entries if e["status"] == status]
        if not status_entries:
            continue
        # Map status to section header
        section_map = {
            "idea": "Idea",
            "scoping": "Scoping",
            "up-next": "Queued",
            "validated": "Validating",
            "done": "Done",
            "canceled": "Canceled",
        }
        section = section_map.get(status, status.replace("-", " ").title())
        lines.append(f"## {section}")
        lines.append("")
        for e in status_entries:
            urgency = e.get("urgency", "?")
            size = e.get("size", "?")
            created = e.get("created", "?")
            title = e.get("title", "Untitled")
            slug = e["_path"].stem
            labels = ", ".join(e.get("labels", []))
            lines.append(f"- **{title}** (`{slug}`) — urgency:{urgency} · size:{size} · created:{created} · labels:{labels}")
        lines.append("")

    # Archive section
    archive_dir = ROADMAP_DIR / "archive"
    archive_entries: list[dict] = []
    if archive_dir.exists():
        for f in sorted(archive_dir.glob("*.md")):
            fm = parse_frontmatter(f)
            if fm is None:
                continue
            fm["_path"] = f
            fm.setdefault("title", f.stem.replace("-", " ").title())
            fm.setdefault("created", "unknown")
            archive_entries.append(fm)

    if archive_entries:
        lines.append("## Archive")
        lines.append("")
        for e in archive_entries:
            slug = e["_path"].stem
            created = e.get("created", "?")
            title = e.get("title", "Untitled")
            lines.append(f"- **{title}** (`{slug}`) — created:{created}")
        lines.append("")

    content = "\n".join(lines)

    # Atomic write: write to temp, rename
    fd, tmp_path = tempfile.mkstemp(dir=ROADMAP_DIR, suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp_path, INDEX_FILE)
    except Exception:
        os.unlink(tmp_path)
        raise

    print(f"Wrote {INDEX_FILE} ({len(entries)} entries)")


if __name__ == "__main__":
    main()
