#!/usr/bin/env python3
"""Migrate Linear tickets to roadmap/*.md files.

Reads /tmp/all-linear-tickets.json (generated by linearis CLI dumps).
Generates frontmatter + body for each ticket into roadmap/{bugs,features,archive}/.
"""
import json
import re
import sys
from pathlib import Path

ROADMAP_DIR = Path("roadmap")
BUGS_DIR = ROADMAP_DIR / "bugs"
FEATURES_DIR = ROADMAP_DIR / "features"
ARCHIVE_DIR = ROADMAP_DIR / "archive"

TYPE_LABELS = {"Bug", "Feature", "Improvement"}
BUCKET_LABELS = {"World Building", "Extraction", "UI", "Balancing", "Tooling", "Tech Debt"}

# Canceled duplicates: same title exists in another status, keep only the non-Canceled version
CANCELED_DUPES = {"TICK-60", "TICK-61", "TICK-62", "TICK-63", "TICK-64", "TICK-65", "TICK-66"}
# TICK-86 is also a Canceled dupe of TICK-60 (both canceled, skip both)
ADDITIONAL_DUPES = {"TICK-86"}
ALL_DUPES = CANCELED_DUPES | ADDITIONAL_DUPES

# Bucket parents: organizational artifacts with zero content
BUCKET_PARENTS = {"TICK-53", "TICK-54", "TICK-55", "TICK-56", "TICK-57", "TICK-58"}

# Status mapping: Linear → roadmap
STATUS_MAP = {
    "Idea": "idea",
    "Backlog": "scoping",
    "Validating": "validated",
    "Completed": "done",
    "Canceled": "canceled",
}

# Priority → urgency
def urgency(p: int) -> int:
    if p is None or p == 0:
        return 4
    return p

def slugify(title: str) -> str:
    s = title.lower()
    s = re.sub(r'\[.*?\]\s*', '', s)  # remove [Prefix] tags
    s = re.sub(r'[^a-z0-9]+', '-', s)
    s = s.strip('-')
    # Truncate to 50 chars, breaking at a word boundary
    if len(s) > 50:
        s = s[:50].rstrip('-')
        # Try to break at last hyphen
        last_hyphen = s.rfind('-')
        if last_hyphen > 30:
            s = s[:last_hyphen]
    return s

def parse_labels(linear_labels: list[dict]) -> tuple[list[str], list[str]]:
    types = []
    buckets = []
    for lbl in linear_labels:
        name = lbl["name"]
        if name in TYPE_LABELS:
            types.append(name)
        elif name in BUCKET_LABELS:
            buckets.append(name)
    return types, buckets

def format_date(iso: str) -> str:
    return iso[:10]

def main():
    source = Path("/tmp/all-linear-tickets.json")
    if not source.exists():
        print("Run this first to generate ticket data:", file=sys.stderr)
        print("  linearis issues list --team TICK --status <status> --limit 200 > /tmp/linear-<status>.json", file=sys.stderr)
        sys.exit(1)

    with open(source) as f:
        all_nodes = json.load(f)

    for d in (BUGS_DIR, FEATURES_DIR, ARCHIVE_DIR):
        d.mkdir(parents=True, exist_ok=True)

    skipped = {"parent": 0, "dupe": 0}
    written = {"bugs": 0, "features": 0, "archive": 0}
    needs_fix = []

    for n in sorted(all_nodes, key=lambda x: x["identifier"]):
        tid = n["identifier"]

        if tid in BUCKET_PARENTS:
            skipped["parent"] += 1
            continue

        if tid in ALL_DUPES:
            skipped["dupe"] += 1
            continue

        title = n["title"]
        status = STATUS_MAP.get(n["state"]["name"], "unknown")
        pri = n["priority"]
        created = format_date(n["createdAt"])
        desc = (n.get("description") or "").replace("\\n", "\n")
        types, buckets = parse_labels(n["labels"]["nodes"])

        is_bug = "Bug" in types
        is_terminal = status in ("done", "canceled")

        if is_terminal:
            target_dir = ARCHIVE_DIR
            written["archive"] += 1
        elif is_bug:
            target_dir = BUGS_DIR
            written["bugs"] += 1
        else:
            target_dir = FEATURES_DIR
            written["features"] += 1

        slug = slugify(title)

        # Track tickets needing post-fix
        if not types or not buckets:
            needs_fix.append(tid)

        labels = types + buckets

        lines = ["---"]
        lines.append(f'title: "{title}"')
        lines.append(f"status: {status}")
        if not is_terminal:
            lines.append(f"urgency: {urgency(pri)}")
            lines.append("size: unknown")
        lines.append(f"created: {created}")
        if labels:
            lines.append("labels:")
            for lbl in labels:
                lines.append(f"  - {lbl}")
        lines.append("---")
        lines.append("")

        # Body: preserve Linear description, stripping any auto-generated preamble
        body = desc.strip()
        if body:
            lines.append(body)
            lines.append("")

        filepath = target_dir / f"{slug}.md"
        # Avoid collisions: if slug already exists, append a suffix
        if filepath.exists():
            idx = 1
            while True:
                candidate = target_dir / f"{slug}-{idx}.md"
                if not candidate.exists():
                    filepath = candidate
                    break
                idx += 1

        filepath.write_text("\n".join(lines))

    print(f"Written: bugs={written['bugs']}, features={written['features']}, archive={written['archive']}")
    print(f"Skipped: bucket_parents={skipped['parent']}, canceled_dupes={skipped['dupe']}")

    if needs_fix:
        print(f"\nTickets needing post-migration label fix ({len(needs_fix)}):")
        for tid in sorted(needs_fix):
            n = next(x for x in all_nodes if x["identifier"] == tid)
            types, buckets = parse_labels(n["labels"]["nodes"])
            print(f"  {tid}: types={types}, buckets={buckets} — {n['title'][:70]}")

if __name__ == "__main__":
    main()
